server:
  port: 8082

spring:
  datasource:
    url : jdbc:mysql://localhost:3306/test
    username : root
    password : pass@word1

  jpa: 
        properties:
          hibernate:
            dialect : org.hibernate.dialect.MySQL5Dialect
        hibernate:
           ddl-auto: update
 