spring:
      datasource:
        url: jdbc:mysql://localhost:3306/test
        username : root
        password : pass@word1
        platform: mysql
        initialize: false
      jpa: 
        database-platform: org.hibernate.dialect.MySQLDialect
        
server:
  port: 8085
  
---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/test
    username: root
    password: root
    initialize: true